# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 947112ed7ec4f65222e986cb58e4a6253fcd511312029142bfd51b749d9a765808f887f2766d1f173c2c43e5762ba5b5027fa986420ff116fa05bcfa8e1f7385

test:
  secret_key_base: d4f0defec1a5d5eb2003e04424fb31cbffa2d8f310a6bdea4f0928049f7a822aa0f4ba6802d1a4ade1686c1b7397bd5b8b2b40e82e734268a7dd948451871475

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
